#docker build -t nome_imagem --build-args ALPINE_VERSION=3.17 .

ARG ALPINE_VERSION=3.18
ARG FRONT_PRD="https://meuapp.com.br"
ARG BACK_PRD="https://meuapp.com.br:3002"

FROM alpine:${ALPINE_VERSION}
#FROM alpine:3.19.0

# RUN apk add --no-cache nodejs
# RUN apk add --no-cache npm
# RUN apk add --no-cache git

# RUN apk add --no-cache nodejs \
#     && apk add --no-cache npm \
#     && apk add --no-cache git 

RUN <<EOF
    apk add --no-cache nodejs
    apk add --no-cache npm
    apk add --no-cache git
EOF

LABEL desenvolvedor="Ramon Silva" descricao="Imagem criada para testes"

ENV FRONT_PRD="https://meuapp.com.br"
ENV BACK_PRD="https://meuapp.com.br:3002"

#declarando sintaxe sem o "="
ENV FRONT_PRD "https://meuapp.com.br"
ENV BACK_PRD "https://meuapp.com.br:3002"

