FROM node:20.10.0-alpine

# RUN apk add --no-cache nodejs
# RUN apk add --no-cache npm
# RUN apk add --no-cache git

# RUN apk add --no-cache nodejs \
#     && apk add --no-cache npm \
#     && apk add --no-cache git 

RUN <<EOF
    apk add --no-cache nodejs
    apk add --no-cache npm
    apk add --no-cache git
EOF

LABEL desenvolvedor="Ramon Silva" descricao="Imagem criada para testes"

# ENV FRONT_PRD="https://meuapp.com.br"
# ENV BACK_PRD="https://meuapp.com.br:3002"

#declarando sintaxe sem o "="
# ENV FRONT_PRD "https://meuapp.com.br"
# ENV BACK_PRD "https://meuapp.com.br:3002"

#Multiplas linhas
ENV FRONT_PRD "https://meuapp.com.br" \ 
    BACK_PRD "https://meuapp.com.br:3002" \
    DESENVOLVEDOR "RAMON" \
    VERSAO "1.0" 

ENV MSG "Variável de ambiente criada no Dockerfile"

RUN echo ${MSG} > /tmp/arquivo_criado_durante__o_build_da_imagem.txt



