#docker build -t nome_imagem --build-args ALPINE_VERSION=3.17 .
ARG ALPINE_VERSION=3.19

FROM alpine:${ALPINE_VERSION}


WORKDIR /
RUN mkdir ./logs/
RUN echo "1 - Diretório de trabalho atual: $(pwd)" > /logs/2.txt

RUN <<EOF
    apk add --no-cache nodejs
    apk add --no-cache npm
EOF

WORKDIR /opt/code/
RUN echo "1 - Diretório de trabalho atual: $(pwd)" > /logs/3.txt


ADD https://argus-academy.com/cursos/docker_-_dominando_a_criacao_e_o_gerenciamento_de_containers/server.tar.gz ./code

RUN tar xvzf server.taz.gz \
    && rm server.taz.gz

CMD [ "/bin/sh", "-c", "Testando comando cmd" ]
